import './globals.css';
import { Dancing_Script } from 'next/font/google';
import { CounterProvider } from './context/CounterProvider'

const dancingscript = Dancing_Script({ subsets: ['latin']});

export const metadata = {
  metadataBase: new URL('https://localhost.com:3000'),
  alternates: {
    canonical: '/',
  },

  title: {
    default: 'Create Next App',
    template: `%s | Next App`,
  },
  description: 'Generated by create app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
  team: React.ReactNode,
  analytics: React.ReactNode,
}) {
  return (
    <html lang="en">
      <body className={dancingscript.className}>
        <CounterProvider>{children}</CounterProvider>
      </body>
    </html>
  );
}